version: '3.7'
services:
  database:
    image: mongo:4.4.1
    restart: always
    volumes:
      - ~/data/db:/data/db
  nuxt-ts:
    build: ./app/
    container_name: nuxt-ts
    restart: always
    ports:
      - '9000:9000'
    command: 'npm run start'
  nginx:
    image: nginx:1.15
    container_name: ngx
    ports:
      - '80:80'
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - nuxt-ts
