version: '3.7'
services:
  database:
    image: mongo:4.4.1
    restart: always
    volumes:
      - /home/iBlog/mongoDB/data/db:/data/db
    networks:
      - iblog-network
  web:
    image: iblog:1.0.0
    depends_on:
      - database
    ports:
      - 9000:9000
    networks:
      - iblog-network
networks:
  iblog-network:
    driver: bridge
