version: '3.7'
services:
  database:
    image: mongo:4.4.1
    restart: always
    ports:
      - 27017:27017
    volumes:
      - /home/Blogger/mongoDB/data/db:/data/db
    networks:
      - blogger-network
  web:
    image: blogger:1.0.1
    restart: always
    depends_on:
      - database
    ports:
      - 9000:9000
    networks:
      - blogger-network
networks:
  blogger-network:
    driver: bridge
